cadastro_processo/urls.py
from django.urls import path

from .views import cadastro_processo

app_name = "cadastro_processo"

urlpatterns = [
    path('', cadastro_processo, name='cadastro')
]

core/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

app_name = "core"

urlpatterns = [
    path('', include(('processo.urls', 'processo'), namespace='processo')),
    path('processo/cadastro_processo/', include(('cadastro_processo.urls', 'cadastro_processo'),
                                                namespace='cadastro_processo')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

processo/urls.py
from django.conf import settings
from django.urls import path
from django.conf.urls.static import static

from .views import IndexView

app_name = "processo"

urlpatterns = [
    path('', IndexView.as_view(), name='index')
]

cadastro_processo/models.py
#!-*- coding: utf8 -*-
"""
   E este arquivo .py tem a finalidade de criar os modelos que seram persistidos no banco de dados.

    author: Ronaldo.Vasconcelos
"""
from django.db import models


class Planilha(models.Model):
    """ Classe que retonará os dados das processos por comarca e uf. """

    nome = models.CharField(verbose_name='Nome', max_length=80)
    cliente = models.CharField(verbose_name='Cliente', max_length=100)
    arquivo = models.FileField()

    class Meta:
        """ Formatação para exibição do admin do django """
        verbose_name = "Processo"
        verbose_name_plural = "Processos"

processo/models.py
#!-*- coding: utf8 -*-
"""
   E este arquivo .py tem a finalidade de criar os modelos que seram persistidos no banco de dados.

    author: Ronaldo.Vasconcelos
"""
from django.db import models


class Processo(models.Model):
    """ Classe que retonará os dados das processos por comarca e uf. """

    pasta = models.CharField(verbose_name='Pasta', max_length=100)
    comarca = models.CharField(verbose_name='Comarca', max_length=100)
    uf = models.CharField(verbose_name='UF', max_length=2)

    class Meta:
        """ Formatação para exibição do admin do django """
        verbose_name = "Processo"
        verbose_name_plural = "Processos"
        ordering = ['uf']

cadastro_processo/forms.py
#!-*- coding: utf8 -*-
"""
    Este arquivo .py tem é o formulario personalizado para criação de um usuário sendo
    possível também usar o email para acessar o portal

    author: Ronaldo.Vasconcelos
"""
from django import forms

from cadastro_processo.models import Planilha


class PlanilhaForm(forms.ModelForm):
    """ Classe que renderiza um formulário do objeto planilha """

    class Meta:
        """ Classe de metadata para o formulario PlanilhaForm """

        model = Planilha
        fields = ('nome', 'cliente', 'arquivo')

processo/forms.py
#!-*- coding: utf8 -*-
"""
    Este arquivo .py tem é o formulario personalizado para criação de um processo sendo
    possível também usar o email para acessar o portal

    author: Ronaldo.Vasconcelos
"""
from django import forms

from .models import Processo


class ProcessoForm(forms.ModelForm):
    """ Classe que renderiza um formulário do objeto processo """

    class Meta:
        """ Classe de metadata para o formulario ProcessoForm """

        model = Processo
        fields = ("pasta", "comarca", "uf")
        widgets = {
            'uf': forms.Select(attrs={"name": "uf"})}

cadastro_processo/controllers.py
#!-*- coding: utf8 -*-
"""
    Este arquivo .py tem a finalidade de executar operações e tratar dados para que
    sejam devolvidos para a view associada.

    author: Ronaldo Vasconcelos
"""
import os

from django.conf import settings
from django.core.files.storage import FileSystemStorage

from cadastro_processo.models import Planilha
from core.custom_exceptions import FormatTypeArchiveException
from processo.models import Processo


class CadastroProcessoController:
    """ Controlador de de Criação de Processos """
    def __init__(self, request, view, *args, **kwargs):
        """
            Inicialização do controlador.
            :param request: Requisição.
            :param view: View associada.
            :param args: args da view.
            :param kwargs: kwargs da view.
        """
        self._request = request
        self._view = view
        self._args = args
        self.kwargs = kwargs
        self._nome = request.POST.get("nome")
        self._cliente = request.POST.get("cliente")
        self._arquivo = request.FILES['arquivo']
        self._message = "O arquivo foi salvo com sucesso."

    def __str__(self):
        """
            Retorna a mensagem referente à execução.
            :return: Instância do controlador.
        """
        return self._message

    def execute(self):
        """
            Executa a criação dos grupos.
            :return: Instância do controlador
        """
        arquivo_carregado = self._arquivo

        if not arquivo_carregado.content_type == "text/csv":
            raise FormatTypeArchiveException(arquivo_carregado.name)

        self._save_processo(arquivo=arquivo_carregado)

        return self

    def _save_processo(self, arquivo):
        """
            Salva os dados do grupo.
            :param desc: Descrição do grupo.
            :return: Instância do controlador.
        """
        # Classe que irá armazenar o arquivo convertidos usando recursos nativa do django
        path = f"{settings.MEDIA_ROOT}/planilhas"
        fs = FileSystemStorage(location=path)

        # Salvando o arquivo
        nome_arquivo = fs.save(name=arquivo.name, content=arquivo)
        caminho = f"{path}/{nome_arquivo}"

        if os.path.exists(caminho):
            with open(caminho, 'r') as var:
                for index, registro in enumerate(var):
                    if not index == 0:
                        pasta, comarca, uf = registro.replace("\n", "").split(";")
                        processo = Processo(pasta=pasta, comarca=comarca, uf=uf)
                        processo.save()

        planilha = Planilha(nome=self._nome, cliente=self._cliente, arquivo=caminho)
        planilha.save()

        return self

cadastro_processo/views.py
#!-*- coding: utf8 -*-
from django.contrib import messages
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView

from core.custom_exceptions import FormatTypeArchiveException
from .models import Planilha
from .forms import PlanilhaForm
from .controllers import CadastroProcessoController


class CadastroProcessoView(CreateView):
    """ Classe de criação de processos """

    model = Planilha
    form_class = PlanilhaForm
    template_name = 'cadastro_processo/processo_create.html'
    success_url = reverse_lazy('processo:index')

    def get_form_class(self):
        """ Retornar o formulario do processo """
        return self.form_class

    def post(self, request, *args, **kwargs):
        """
            Função que recebe o nome do grupo, a campanha ao qual o grupo esta associado e a
            quantidade de grupos quer criar indicando um número inicial para o título do grupo.
        """
        try:
            messages.success(request, CadastroProcessoController(request=request, view=self, *args,
                                                                 **kwargs).execute())
        except FormatTypeArchiveException as format_erro:
            messages.error(request, format_erro)
            return render(request, self.template_name, {'form': self.get_form()})
        except Exception as ex:
            messages.error(request, ex)
            return render(request, self.template_name, {'form': self.get_form()})

        return redirect(self.success_url)


cadastro_processo = CadastroProcessoView.as_view()

processo/views.py
# coding=utf-8
""" E este arquivo .py tem uma das finalidades a exibição desses dados na tela

    author: Ronaldo.Vasconcelos
"""
from django.views.generic import ListView
from .models import Processo


class IndexView(ListView):

    model = Processo
    template_name = 'processo/processo_list.html'
    context_object_name = 'object_list'
    paginate_by = 6

    def get_queryset(self):
        """
            Função responsavel por consultar todos os processos cadastrados
        """
        return Processo.objects.all()

    """ Classe herdada do generic view do Django para exibição da tela principal do portal """

cadastro_processo/templates/cadastro_processo/processo_create.html
{% extends 'processo/base.html' %}
{% load widget_tweaks %}

{% block title %} Cadastrar Processo {% endblock title %}

{% block container %}
<div id="alert">
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            {{ message }}
        </div>
        {% endfor %}
    </ul>
    {% endif %}
</div>

<h2> Cadastrar Processo </h2>

<br/>

<form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <fieldset>
        <div class="form-group{% if field.errors %} has-error{% endif %}">
            <label for="nome" class="col-sm-2 control-label">{{ form.nome.label }}</label>
            <div class="col-md-6">
                {% render_field form.nome id="nome" class="form-control" %}
                {% for error in form.nome.errors %}
                <span class="help-block">{{ error }}</span>
                {% endfor %}
            </div>
        </div>
        <div class="form-group{% if field.errors %} has-error{% endif %}">
            <label for="cliente" class="col-sm-2 control-label">{{ form.cliente.label }}</label>
            <div class="col-md-6">
                {% render_field form.cliente id="cliente" class="form-control" %}
                {% for error in form.cliente.errors %}
                <span class="help-block">{{ error }}</span>
                {% endfor %}
            </div>
        </div>
         <div class="form-group{% if field.errors %} has-error{% endif %}">
            <label class="col-sm-2 control-label">Arquivo</label>
            <div class="col-md-6">
                {% render_field form.arquivo class="form-control" %}
                {% for error in form.arquivo.errors %}
                <span class="help-block">{{ error }}</span>
                {% endfor %}
            </div>
        </div>
        <hidden class="col-sm-4 control-label"></hidden>
        <a id="botao_voltar" href="{% url 'processo:index' %}" type="submit" style="margin-left:5.8%;"
           class="btn btn-secundary">
            Voltar
        </a>
        <button id="botao_converter" type="submit" style="margin-left:5.8%;" class="btn btn-success">
            Inserir Arquivo
        </button>
    </fieldset>
</form>
{% endblock %}

processo/templates/processo/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="utf-8">

    <title> {% block title %} Urbano Vitalino {% endblock %} </title>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <link rel="stylesheet" href="{% static 'assets/bootstrap.min.css' %}" media="screen"/>
    <link rel="stylesheet" href="{% static 'assets/custom.min.css' %}" media="screen"/>

    <script type="text/javascript">
        window.setTimeout(function() {
            $(".alert").fadeTo(500, 0).slideUp(500, function(){
                $(this).remove();
            });
         }, 5000);

    </script>
</head>
<body>
<div class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <a href="{% url 'processo:index' %}" class="navbar-brand">Urbano Vitalino</a>
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'cadastro_processo:cadastro' %}"> Cadastrar Processo </a></li>
            </ul>
        </div>
    </div>
</div>
<div class="container margin-top" style="margin-top:20px">
    {% block messages %}
    {% for message in messages %}
    <div class="alert {{ message.tags }} alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        {{ message }}
    </div>
    {% endfor %}
    {% endblock %}
    {% block container %} {% endblock %}
    <footer>
        <div class="row">
            <div class="col-lg-12">
                <ul class="list-unstyled">
                    <li class="pull-right"><a href="#top">Voltar ao Topo</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>
<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
<script src="{% static 'assets/bootstrap.min.js' %}"></script>
</body>
</html>

processo/templates/processo/pagination.html
<div class="row">
    <div class="col-md-12">
        <nav>
            <ul class="pagination">
                {% for page in paginator.page_range %}
                <li {% if page_obj.number == page%} class="active" {% endif %}><a href="?page={{page}}"> {{ page }} </a></li>
                {% endfor %}
            </ul>
        </nav>
    </div>
</div>

processo/templates/processo/processo_list.html
{% extends "processo/base.html" %}
{% load pagination %}

{% block title %} Listagem de Processos | {{block.super}} {% endblock%}

{% block container%}
<div class="page-header">
    <h2>Processos</h2>
</div>
<div class="row">
   <table class="table table-striped table-bordered">
    <thead>
    <tr>
        <th>
            Pasta
        </th>
        <th>
            Comarca
        </th>
        <th>
            UF
        </th>
    </tr>
    </thead>
    <tbody>
        {% for processo in object_list %}
        <tr>
            <td>
                {{ processo.pasta }}
            </td>
            <td>
                {{ processo.comarca }}
            </td>
            <td>
                {{ processo.uf }}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>

{% pagination request paginator page_obj %}
{% endblock %}